-- Pinned UniFi Protect camera view (unifi-overlay shell plugin).
--
-- bin/unifi-protect launches mpv with a dedicated app-id per size preset, which
-- is what keeps this window out of mpv's generic centered-float rules and lets
-- it land in the corner instead. Presets are 16:9 and scale from monitor height
-- so they hold the same share of the screen on any display.
--
-- `move` restates the width expression rather than using `window_w`: the rule is
-- evaluated before the window has been sized, so `window_w` reads as 0 there and
-- the view lands mid-screen. webcam-overlay.lua in the Omarchy defaults does the
-- same thing for the same reason.

-- Single camera.
o.window("^omarchy-unifi-pip-small$", {
  size = { "(monitor_h*4/15)", "(monitor_h*3/20)" },
  move = { "(monitor_w-monitor_h*4/15-20)", "(monitor_h*0.04)" },
})
o.window("^omarchy-unifi-pip-medium$", {
  size = { "(monitor_h*1/3)", "(monitor_h*3/16)" },
  move = { "(monitor_w-monitor_h*1/3-20)", "(monitor_h*0.04)" },
})
o.window("^omarchy-unifi-pip-large$", {
  size = { "(monitor_h*4/9)", "(monitor_h/4)" },
  move = { "(monitor_w-monitor_h*4/9-20)", "(monitor_h*0.04)" },
})

-- Grid mode packs four feeds into one window, so every preset is a step larger
-- than its single-camera equivalent — a quarter of a small view is unreadable.
o.window("^omarchy-unifi-grid-small$", {
  size = { "(monitor_h*4/9)", "(monitor_h/4)" },
  move = { "(monitor_w-monitor_h*4/9-20)", "(monitor_h*0.04)" },
})
o.window("^omarchy-unifi-grid-medium$", {
  size = { "(monitor_h*3/5)", "(monitor_h*27/80)" },
  move = { "(monitor_w-monitor_h*3/5-20)", "(monitor_h*0.04)" },
})
o.window("^omarchy-unifi-grid-large$", {
  size = { "(monitor_h*4/5)", "(monitor_h*9/20)" },
  move = { "(monitor_w-monitor_h*4/5-20)", "(monitor_h*0.04)" },
})

-- Shared treatment: floats above everything, follows you across workspaces, and
-- never takes focus — clicking it leaves your keyboard where it was.
--
-- No keep_aspect_ratio: the presets are already 16:9, and letting Hyprland
-- re-fit the window once mpv learns the video size moves it back out of the
-- corner after the move rule has already run.
--
-- Hyprland 0.56 has no click-through rule (no_input/noinput/nofocus are not
-- fields it knows), so no_focus is as close as the compositor gets. Opacity is
-- applied live by the plugin via hl.dsp.window.set_prop instead of here, so
-- changing it in settings doesn't need a config reload.
o.window({ class = "^omarchy-unifi-(pip|grid)-(small|medium|large)$" }, {
  tag = "-default-opacity",
  float = true,
  pin = true,
  no_initial_focus = true,
  no_focus = true,
  no_dim = true,
  border_size = 0,
  opacity = "1 1",
})

-- The "open it properly" window is an ordinary float, centered and focusable.
o.window("^omarchy-unifi-window$", {
  tag = "-default-opacity",
  float = true,
  center = true,
  size = { 1280, 720 },
  keep_aspect_ratio = true,
  opacity = "1 1",
})

-- Optional single-display lock, generated by the plugin when you pick a monitor
-- in settings. Absent until then, so the view follows whichever screen is active.
pcall(require, "hypr.unifi_overlay_monitor")
